### ISSUE TITLE
Kerberos ipa-replica error

### ISSUE THREAD

**Issue by diniguezcabrera** [freeipa/ansible-freeipa#285]
I have a freeipa server that I installed with the ipaserver role and I installed a certificate in order to have ssl in the web UI, following the steps (manually):

1. Copy the certificate /etc/ssl/certs that contains: root-intermediate.crt, cert.key, cert.cert, intermediate.crt
2. Kinit
3. ipa-cacert-manage install /etc/ssl/certs/root-intermediate.crt
4. ipa-server-certinstall -p {{ ipaadmin_password }} -w -d /etc/ssl/certs/cert.key /etc/ssl/certs/cert.crt /etc/ssl/certs/intermediate.crt (WITHOUT key unlock password)

When I try to use the ipareplica role, previously only copying the certs in the ipareplica in /etc/ssl/certs (step 1), but not following the rest of the steps,  I have the following error:

```
TASK [ipareplica : Install - Add to ipaservers] *******************************************************************************************************************************************************************

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipalib/krb_utils.py", line 168, in get_principal
    creds = get_credentials(ccache_name=ccache_name)
  File "/usr/lib/python3.6/site-packages/ipalib/krb_utils.py", line 147, in get_credentials
    return gssapi.Credentials(usage='initiate', name=name, store=store)
  File "/usr/lib64/python3.6/site-packages/gssapi/creds.py", line 64, in __new__
    store=store)
  File "/usr/lib64/python3.6/site-packages/gssapi/creds.py", line 137, in acquire
    mechs, usage)
  File "gssapi/raw/creds.pyx", line 158, in gssapi.raw.creds.acquire_cred
gssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): No Kerberos credentials available (default cache: )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.ansible/tmp/ansible-tmp-1590509881.7647336-162808-92865601599556/AnsiballZ_ipareplica_add_to_ipaservers.py", line 102, in <module>
    _ansiballz_main()
  File "/home/username/.ansible/tmp/ansible-tmp-1590509881.7647336-162808-92865601599556/AnsiballZ_ipareplica_add_to_ipaservers.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/username/.ansible/tmp/ansible-tmp-1590509881.7647336-162808-92865601599556/AnsiballZ_ipareplica_add_to_ipaservers.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.ipareplica_add_to_ipaservers', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ipareplica_add_to_ipaservers_payload_vfvdnqkw/ansible_ipareplica_add_to_ipaservers_payload.zip/ansible/modules/ipareplica_add_to_ipaservers.py", line 148, in <module>
  File "/tmp/ansible_ipareplica_add_to_ipaservers_payload_vfvdnqkw/ansible_ipareplica_add_to_ipaservers_payload.zip/ansible/modules/ipareplica_add_to_ipaservers.py", line 131, in main
  File "/usr/lib/python3.6/site-packages/ipalib/backend.py", line 69, in connect
    conn = self.create_connection(*args, **kw)
  File "/usr/lib/python3.6/site-packages/ipaserver/plugins/ldap2.py", line 196, in create_connection
    principal = krb_utils.get_principal(ccache_name=ccache)
  File "/usr/lib/python3.6/site-packages/ipalib/krb_utils.py", line 171, in get_principal
    raise errors.CCacheError(message=unicode(e))
ipalib.errors.CCacheError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): No Kerberos credentials available (default cache: )
fatal: [domain2.name.com]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to domain2.name.com closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/usr/lib/python3.6/site-packages/ipalib/krb_utils.py\", line 168, in get_principal\r\n    creds = get_credentials(ccache_name=ccache_name)\r\n  File \"/usr/lib/python3.6/site-packages/ipalib/krb_utils.py\", line 147, in get_credentials\r\n    return gssapi.Credentials(usage='initiate', name=name, store=store)\r\n  File \"/usr/lib64/python3.6/site-packages/gssapi/creds.py\", line 64, in __new__\r\n    store=store)\r\n  File \"/usr/lib64/python3.6/site-packages/gssapi/creds.py\", line 137, in acquire\r\n    mechs, usage)\r\n  File \"gssapi/raw/creds.pyx\", line 158, in gssapi.raw.creds.acquire_cred\r\ngssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): No Kerberos credentials available (default cache: )\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/username/.ansible/tmp/ansible-tmp-1590509881.7647336-162808-92865601599556/AnsiballZ_ipareplica_add_to_ipaservers.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/username/.ansible/tmp/ansible-tmp-1590509881.7647336-162808-92865601599556/AnsiballZ_ipareplica_add_to_ipaservers.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/username/.ansible/tmp/ansible-tmp-1590509881.7647336-162808-92865601599556/AnsiballZ_ipareplica_add_to_ipaservers.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.ipareplica_add_to_ipaservers', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ipareplica_add_to_ipaservers_payload_vfvdnqkw/ansible_ipareplica_add_to_ipaservers_payload.zip/ansible/modules/ipareplica_add_to_ipaservers.py\", line 148, in <module>\r\n  File \"/tmp/ansible_ipareplica_add_to_ipaservers_payload_vfvdnqkw/ansible_ipareplica_add_to_ipaservers_payload.zip/ansible/modules/ipareplica_add_to_ipaservers.py\", line 131, in main\r\n  File \"/usr/lib/python3.6/site-packages/ipalib/backend.py\", line 69, in connect\r\n    conn = self.create_connection(*args, **kw)\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/plugins/ldap2.py\", line 196, in create_connection\r\n    principal = krb_utils.get_principal(ccache_name=ccache)\r\n  File \"/usr/lib/python3.6/site-packages/ipalib/krb_utils.py\", line 171, in get_principal\r\n    raise errors.CCacheError(message=unicode(e))\r\nipalib.errors.CCacheError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529639053): No Kerberos credentials available (default cache: )\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

This is my playbook:

```
- hosts: ipareplicas
  become: yes
  roles:
    # - role: ipaserver
    #   state: present
    - role: ipareplica
      state: present
      vars:
        ipaserver_hostname: domain.name.com
        ipaserver_domain: name.com
        ipaserver_realm: NAME.COM
        ipaadmin_password: pass
        ipadm_password: pass
        ipassd_enable_dns_updates: true
        ipaadmin_principal: admin
```

**Comment by t-woerner** [comment]
This is a ccache error. Do you have changes in the environment for the deployment? Which IPA version are you using on the affected node?
