### ISSUE TITLE
freeipa version '4.5.4' is too old

### ISSUE THREAD

**Issue by Seep1959** [freeipa/ansible-freeipa#33]
I'm trying to install a freeipa replica using the replica playbook and I am getting the error "freeipa version '4.5.4" is too old". This is a fresh centos-7 image, the replica readme lists 4.5+ supported. 

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zn5TjK/ansible_module_ipareplica_test.py", line 53, in <module>
    from ansible.module_utils.ansible_ipa_replica import *
  File "/tmp/ansible_zn5TjK/ansible_modlib.zip/ansible/module_utils/ansible_ipa_replica.py", line 119, in <module>
Exception: freeipa version '4.5.4' is too old

fatal: [ipa03.dev.domain.tld]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_zn5TjK/ansible_module_ipareplica_test.py\", line 53, in <module>\n    from ansible.module_utils.ansible_ipa_replica import *\n  File \"/tmp/ansible_zn5TjK/ansible_modlib.zip/ansible/module_utils/ansible_ipa_replica.py\", line 119, in <module>\nException: freeipa version '4.5.4' is too old\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

**Comment by t-woerner** [comment]
Some adaptions are needed to make replica working with FreeIPA 4.5.

**Comment by rjeffman** [comment]
Documentation already states that only FreeIPA 4.6+ is supported for replica installations, and FreeIPA 4.5 series is not supported anymore, therefore I'm closing this issue.

If this solution is not enough, please reopen this issue stating the reasons, or open a new issue.
