### ISSUE TITLE
Problem installing IPA on latest CentOS 8.2

### ISSUE THREAD

**Issue by rduffner** [freeipa/ansible-freeipa#439]
I have this issue:

https://access.redhat.com/solutions/5527751

```
TASK [ipaserver : Install - Setup CA] ****************************************************************************************************************************************************************************************************************************************************************************************
fatal: [ipa-ansible1.ipa.example.org]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ipa-ansible1.ipa.example.org closed.\r\n", "module_stdout": "Failed to configure CA instance: CalledProcessError(Command ['/usr/sbin/pkispawn', '-s', 'CA', '-f', '/tmp/tmpih0s21kj'] returned non-zero exit status 1: 'Notice: Trust flag u is set automatically if the private key is present.\\nERROR: Exception: Server unreachable due to SSL error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)\\n  File \"/usr/lib/python3.6/site-packages/pki/server/pkispawn.py\", line 562, in main\\n    scriptlet.spawn(deployer)\\n  File \"/usr/lib/python3.6/site-packages/pki/server/deployment/scriptlets/configuration.py\", line 836, in spawn\\n    request_timeout=status_request_timeout,\\n  File \"/usr/lib/python3.6/site-packages/pki/server/deployment/pkihelper.py\", line 911, in wait_for_startup\\n    raise Exception(\\'Server unreachable due to SSL error: %s\\' % reason) from exc\\n\\n')\r\nSee the installation logs and the following files/directories for more information:\r\n  /var/log/pki/pki-tomcat\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py\", line 188, in spawn_instance\r\n    ipautil.run(args, nolog=nolog_list)\r\n  File \"/usr/lib/python3.6/site-packages/ipapython/ipautil.py\", line 598, in run\r\n    p.returncode, arg_string, output_log, error_log\r\nipapython.ipautil.CalledProcessError: CalledProcessError(Command ['/usr/sbin/pkispawn', '-s', 'CA', '-f', '/tmp/tmpih0s21kj'] returned non-zero exit status 1: 'Notice: Trust flag u is set automatically if the private key is present.\\nERROR: Exception: Server unreachable due to SSL error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)\\n  File \"/usr/lib/python3.6/site-packages/pki/server/pkispawn.py\", line 562, in main\\n    scriptlet.spawn(deployer)\\n  File \"/usr/lib/python3.6/site-packages/pki/server/deployment/scriptlets/configuration.py\", line 836, in spawn\\n    request_timeout=status_request_timeout,\\n  File \"/usr/lib/python3.6/site-packages/pki/server/deployment/pkihelper.py\", line 911, in wait_for_startup\\n    raise Exception(\\'Server unreachable due to SSL error: %s\\' % reason) from exc\\n\\n')\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/rduffner/.ansible/tmp/ansible-tmp-1605475953.60599-1820-214547578297248/AnsiballZ_ipaserver_setup_ca.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/rduffner/.ansible/tmp/ansible-tmp-1605475953.60599-1820-214547578297248/AnsiballZ_ipaserver_setup_ca.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/rduffner/.ansible/tmp/ansible-tmp-1605475953.60599-1820-214547578297248/AnsiballZ_ipaserver_setup_ca.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.ipaserver_setup_ca', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ipaserver_setup_ca_payload_g3j24pj0/ansible_ipaserver_setup_ca_payload.zip/ansible/modules/ipaserver_setup_ca.py\", line 355, in <module>\r\n  File \"/tmp/ansible_ipaserver_setup_ca_payload_g3j24pj0/ansible_ipaserver_setup_ca_payload.zip/ansible/modules/ipaserver_setup_ca.py\", line 317, in main\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/ca.py\", line 355, in install_step_0\r\n    pki_config_override=options.pki_config_override,\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/cainstance.py\", line 480, in configure_instance\r\n    self.start_creation(runtime=runtime)\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/service.py\", line 603, in start_creation\r\n    run_step(full_msg, method)\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/service.py\", line 589, in run_step\r\n    method()\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/cainstance.py\", line 596, in __spawn_instance\r\n    nolog_list=nolog_list\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py\", line 190, in spawn_instance\r\n    self.handle_setup_error(e)\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/dogtaginstance.py\", line 423, in handle_setup_error\r\n    raise RuntimeError(\"%s configuration failed.\" % self.subsystem)\r\nRuntimeError: CA configuration failed.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

TASK [ipaserver : Cleanup temporary files] ***********************************************************************************************************************************************************************************************************************************************************************************
ok: [ipa-ansible1.ipa.example.org] => (item=/etc/ipa/.tmp_pkcs12_dirsrv)
ok: [ipa-ansible1.ipa.example.org] => (item=/etc/ipa/.tmp_pkcs12_http)
ok: [ipa-ansible1.ipa.example.org] => (item=/etc/ipa/.tmp_pkcs12_pkinit)
```

```
[root@ipa-ansible1 pki]# cat pki-ca-spawn.20201115223237.log
2020-11-15 22:33:11 ERROR: Exception: Server unreachable due to SSL error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)
  File "/usr/lib/python3.6/site-packages/pki/server/pkispawn.py", line 562, in main
    scriptlet.spawn(deployer)
  File "/usr/lib/python3.6/site-packages/pki/server/deployment/scriptlets/configuration.py", line 836, in spawn
    request_timeout=status_request_timeout,
  File "/usr/lib/python3.6/site-packages/pki/server/deployment/pkihelper.py", line 911, in wait_for_startup
    raise Exception('Server unreachable due to SSL error: %s' % reason) from exc
```

According to the RedHat KB entry, I should downgrade the jdk with

```
dnf downgrade -y java-1.8.0-openjdk java-1.8.0-openjdk-headless
```

But that does not work:

```
[root@ipa-ansible1 pki]# dnf downgrade -y java-1.8.0-openjdk java-1.8.0-openjdk-headless
Last metadata expiration check: 0:27:16 ago on Sun 15 Nov 2020 10:17:28 PM CET.
Package java-1.8.0-openjdk of lowest version already installed, cannot downgrade it.
Package java-1.8.0-openjdk-headless of lowest version already installed, cannot downgrade it.
Dependencies resolved.
Nothing to do.
Complete!
```

I tried to manually install 265 instead of 272, but it seems whenever the dependencies are installed, 272 is installed anyway.

I don't really want to wait until CentOS 8.3 hits, which should fix it (given that RHEL 8.3 supposedly fixes it).

**Comment by rduffner** [comment]
OK, this seems to fix it.

https://forums.centos.org/viewtopic.php?t=76238&p=320510

Maybe google some more next time. Left here for posterity in case someone stumbles over this, too.

**Comment by rjeffman** [comment]
This is a PKI/Java known issue. Fortunatelly, there is a workaround for now.

I'm closing this issue, due to that. If you think it should be kept open, please, reopen it, and let us know why.
