### ISSUE TITLE
ipaserver role - Fails on ipaclient install

### ISSUE THREAD

**Issue by jlanclos** [freeipa/ansible-freeipa#61]
When executing the ipaserver role, the following error occurs when executing "TASK [ipaclient : Install - IPA client test]"

Logs show ansible-ipaclient_test was invoked with correct domain setting.

```
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_ipaclient_test_payload_zc2iAK/__main__.py", line 890, in <module>
  File "/tmp/ansible_ipaclient_test_payload_zc2iAK/__main__.py", line 333, in main
TypeError: validate_domain_name() got an unexpected keyword argument 'entity'

```

System is running the following versions:

ipa-client-common-4.6.4-10.el7.centos.3.noarch
ipa-server-4.6.4-10.el7.centos.3.x86_64
ipa-server-common-4.6.4-10.el7.centos.3.noarch
ipa-client-4.6.4-10.el7.centos.3.x86_64
ansible-2.7.9-1.el7.noarch
ipa-server-dns-4.6.4-10.el7.centos.3.noarch

**Comment by jlanclos** [comment]
Reverting to commit 7c378d9c4df144680ad9fc464ab7f8f3c5153a30 resolves this issue.

Entity parameter for validate_domain_name was added around 4.7 with the following commit: https://github.com/freeipa/freeipa/commit/905ab93c958a539eb4af7d4b008a5aa02292ba12

Documentation states: "The client role should also be functional with FreeIPA 4.4."
So shouldn't the ipaclient role limit function/modthod calls to the ones present in ipalib for 4.4, or at least inspect methods/functions being called to ensure correct parameter set is supported?

**Comment by jlanclos** [comment]
Diff to resolve ipaclient_test issues with pre 4.7 client librareis:
```
--- a/roles/ipaclient/library/ipaclient_test.py
+++ b/roles/ipaclient/library/ipaclient_test.py
@@ -325,9 +325,12 @@ def main():
         ### ServiceInstallInterface ###
 
         validate_domain_name(options.domain_name)
-
+        
         if options.realm_name:
-            validate_domain_name(options.realm_name, entity="realm")
+           if IPA_PYTHON_VERSION >= 40700:
+              validate_domain_name(options.realm_name, entity="realm")
+           else:
+              validate_domain_name(options.realm_name)
 
         ### ClientInstallInterface ###
 
@@ -481,7 +484,8 @@ def main():
         #        "IPA client is already configured on this system.",
         #        rval=CLIENT_ALREADY_CONFIGURED)
 
-        check_ldap_conf()
+       if IPA_PYTHON_VERSION >= 407000:
+          check_ldap_conf()
 
         if options.conf_ntp:
             try:
@@ -524,7 +528,7 @@ def main():
                 rval=CLIENT_INSTALL_ERROR)
 
         # --no-sssd is not supported any more for rhel-based distros
-        if not tasks.is_nosssd_supported() and not options.sssd:
+        if not options.sssd and not tasks.is_nosssd_supported():
             raise ScriptError(
                 "Option '--no-sssd' is incompatible with the 'authselect' tool "
                 "provided by this distribution for configuring system "
@@ -532,7 +536,7 @@ def main():
                 rval=CLIENT_INSTALL_ERROR)
 
         # --noac is not supported any more for rhel-based distros
-        if not tasks.is_nosssd_supported() and options.no_ac:
+        if options.no_ac and not tasks.is_nosssd_supported():
             raise ScriptError(
                 "Option '--noac' is incompatible with the 'authselect' tool "
                 "provided by this distribution for configuring system "

```

However now there is another failure in ipaclient_api.py
The calls to api.Backend.rpcclient.forward are also returning the INFO logging:
```
fatal: [infra2.example.com]: FAILED! => {
    "changed": false, 
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 104: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 8861
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
Shared connection to infra2.example.com closed.
", 
    "module_stdout": "trying https://infra1.example.com/ipa/json
[try 1]: Forwarding 'ping' to json server 'https://infra1.example.com/ipa/json'
[try 1]: Forwarding 'ca_is_enabled' to json server 'https://infra1.example.com/ipa/json'
[try 1]: Forwarding 'config_show/1' to json server 'https://infra1.example.com/ipa/json'

{\"ca_enabled\": true, \"invocation\": {\"module_args\": {\"debug\": false, \"hostname\": \"infra2.example.com\", \"realm\": \"EXAMPLE.COM\", \"servers\": [\"infra1.example.com\"]}}, \"changed\": true, \"subject_base\": \"O=EXAMPLE.COM\"}
", 
    "msg": "MODULE FAILURE
See stdout/stderr for the exact error", 
    "rc": 0
}
```
