### ISSUE TITLE
ipareplica_setup_kra fails

### ISSUE THREAD

**Issue by jlanclos** [freeipa/ansible-freeipa#64]
ipareplia role fails with following message when ipareplica_setup_kra is set to yes

```
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_ipareplica_setup_kra_payload_WR8ZEw/__main__.py", line 235, in <module>
  File "/tmp/ansible_ipareplica_setup_kra_payload_WR8ZEw/__main__.py", line 228, in main
  File "/usr/lib/python2.7/site-packages/ipaserver/install/kra.py", line 97, in install
    replica_config.dirman_password)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/custodiainstance.py", line 325, in get_kra_keys
    self._get_keys(cacerts_file, cacerts_pwd, data)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/custodiainstance.py", line 280, in _get_keys
    value = cli.fetch_key(os.path.join(prefix, nickname), False)
  File "/usr/lib/python2.7/site-packages/ipaserver/secrets/client.py", line 105, in fetch_key
    r.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
```

**Comment by t-woerner** [comment]
Please try again with the 0.1.0 release. There have been several enhancements and fixes also related to KRA.

**Comment by jlanclos** [comment]
Tried with 0.1.6 and master branches. Same failure.

**Comment by t-woerner** [comment]
A t of changes have been done also lately. The next release after 0.1.12 will provide working KRA with 7a2eaa6f535b1353d46bcfa8b0b2484b15ff3863

**Comment by t-woerner** [comment]
Have you been able to give 0.2.0 or 0.2.1 a try?
