### ISSUE TITLE
ipaclient fails when ipaclient_use_otp is true and client has no dns entry yet

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#74]
when ipaclient_use_otp is set to true and the client does not yet have a dns entry in the ipa dns, it fails.

fatal: [ipaclient.example.com -> ipa01.example.com]: FAILED! => {
    "changed": false,
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "ansible_python_interpreter": "/usr/bin/python2",
            "ccache": "/root/.ansible/tmp/ansible-tmp-1555507414.4304569-5411027979932/ccache",
            "certificates": null,
            "fqdn": "ipaclient.example.com",
            "ipaddress": null,
            "principal": "admin",
            "random": true,
            "sshpubkey": null,
            "state": "present"
        }
    },
    "msg": "ipaclient_get_otp module failed : Host 'ipaclient.example.com' does not have corresponding DNS A/AAAA record"
}

Rob

**Comment by RobVerduijn** [comment]
it still breaks at the task:
ipareplica : Install - DS enable SSL
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1555586842.4990764-62135770002703/AnsiballZ_ipareplica_ds_enable_ssl.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1555586842.4990764-62135770002703/AnsiballZ_ipareplica_ds_enable_ssl.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1555586842.4990764-62135770002703/AnsiballZ_ipareplica_ds_enable_ssl.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ipareplica_ds_enable_ssl_payload_USSGXL/__main__.py", line 191, in <module>
  File "/tmp/ansible_ipareplica_ds_enable_ssl_payload_USSGXL/__main__.py", line 184, in main
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 358, in enable_ssl
    self.start_creation()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 570, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 560, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 855, in __enable_ssl
    resubmit_timeout=api.env.replication_wait_timeout
  File "/usr/lib/python2.7/site-packages/ipalib/install/certmonger.py", line 356, in request_and_wait_for_cert
    "Certificate issuance failed ({}: {})".format(state, ca_error)
RuntimeError: Certificate issuance failed (CA_UNCONFIGURED: Error setting up ccache for "host" service on client using default keytab: Keytab contains no suitable keys for host/localhost@.)

Rob

**Comment by t-woerner** [comment]
This is a bug and needs to be addressed.
