### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by chicofranchico** [freeipa/ansible-freeipa#86]
The following line fails on python3 with the above mentioned error:

https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaserver/library/ipaserver_test.py#L477

Stack trace:

```TASK [ipaserver : Install - Server installation test] ******************************************************************************************************************************************************
task path: /Volumes/example/example-ops/ansible/external/ansible-freeipa/roles/ipaserver/tasks/install.yml:30
Using module file /Volumes/example/example-ops/ansible/external/ansible-freeipa/roles/ipaserver/library/ipaserver_test.py
Pipelining is enabled.
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: fedora
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="fedora"' -o ConnectTimeout=90 -o ControlPath=/Users/localuser/.ansible/cp/ansible-ssh-%C 1.2.3.4 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qitwvzlnofhsbznpyjxhgbhvrhydlpuv ; /usr/bin/python3'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<1.2.3.4> (1, b'BECOME-SUCCESS-qitwvzlnofhsbznpyjxhgbhvrhydlpuv\n', b'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/localuser/.ssh/config\r\ndebug1: /Users/localuser/.ssh/config line 3: Applying options for *\r\ndebug1: /Users/localuser/.ssh/config line 88: Applying options for 1.2.3.4\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 1.2.3.4 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 59387\r\ndebug3: mux_client_request_session: session request sent\r\n<stdin>:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module\'s documentation for alternative uses\nTraceback (most recent call last):\n  File "<stdin>", line 114, in <module>\n  File "<stdin>", line 106, in _ansiballz_main\n  File "<stdin>", line 49, in invoke_module\n  File "/usr/lib64/python3.7/imp.py", line 234, in load_module\n    return load_source(name, filename, file)\n  File "/usr/lib64/python3.7/imp.py", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File "<frozen importlib._bootstrap>", line 630, in _exec\n  File "<frozen importlib._bootstrap_external>", line 728, in exec_module\n  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\n  File "/tmp/ansible_ipaserver_test_payload_1h44scru/__main__.py", line 701, in <module>\n  File "/tmp/ansible_ipaserver_test_payload_1h44scru/__main__.py", line 477, in main\nAttributeError: \'str\' object has no attribute \'decode\'\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
<1.2.3.4> Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/localuser/.ssh/config
debug1: /Users/localuser/.ssh/config line 3: Applying options for *
debug1: /Users/localuser/.ssh/config line 88: Applying options for 1.2.3.4
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: resolve_canonicalize: hostname 1.2.3.4 is address
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 59387
debug3: mux_client_request_session: session request sent
<stdin>:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/usr/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.7/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_ipaserver_test_payload_1h44scru/__main__.py", line 701, in <module>
  File "/tmp/ansible_ipaserver_test_payload_1h44scru/__main__.py", line 477, in main
AttributeError: 'str' object has no attribute 'decode'
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
fatal: [freeipa01.example.net]: FAILED! => changed=false
  module_stderr: |-
    OpenSSH_7.9p1, LibreSSL 2.7.3
    debug1: Reading configuration data /Users/localuser/.ssh/config
    debug1: /Users/localuser/.ssh/config line 3: Applying options for *
    debug1: /Users/localuser/.ssh/config line 88: Applying options for 1.2.3.4
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 48: Applying options for *
    debug2: resolve_canonicalize: hostname 1.2.3.4 is address
    debug1: auto-mux: Trying existing master
    debug2: fd 3 setting O_NONBLOCK
    debug2: mux_client_hello_exchange: master version 4
    debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
    debug3: mux_client_request_session: entering
    debug3: mux_client_request_alive: entering
    debug3: mux_client_request_alive: done pid = 59387
    debug3: mux_client_request_session: session request sent
    <stdin>:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    Traceback (most recent call last):
      File "<stdin>", line 114, in <module>
      File "<stdin>", line 106, in _ansiballz_main
      File "<stdin>", line 49, in invoke_module
      File "/usr/lib64/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib64/python3.7/imp.py", line 169, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 630, in _exec
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_ipaserver_test_payload_1h44scru/__main__.py", line 701, in <module>
      File "/tmp/ansible_ipaserver_test_payload_1h44scru/__main__.py", line 477, in main
    AttributeError: 'str' object has no attribute 'decode'
    debug3: mux_client_read_packet: read header failed: Broken pipe
    debug2: Received exit status from master 1
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

ansible 2.8.1 and python version = 3.7.3 (default, Mar 30 2019, 12:27:20) [Clang 10.0.1 (clang-1001.0.46.3)]

**Comment by t-woerner** [comment]
Oh, that is a python2 only remain.

**Comment by chicofranchico** [comment]
Thanks a bunch!
